### PR TITLE
Removing erroneous print statement

### PR DESCRIPTION
**Pull request by tsm1th**
Stumbled upon a print statement that needs to be removed.

### CODE REVIEW

**Comment by Kircheneer** [comment]
Thanks for the submission! We're just missing the change log fragment :)

**Comment by tsm1th** [comment]
Sorry about that, just added it.

**Comment by jdrew82** [comment]
@tsm1th thanks for submitting this! I was just talking to @qduk about this the other day.

**Comment by qduk** [comment]
@jdrew82  I knew I was forgetting about something yesterday!  Thanks @tsm1th taking care of my mistake!

**Comment by tsm1th** [comment]
@qduk - No problem!  I do it all the time :)

**Review by jdrew82 — APPROVED** [review]
LGTM!

**Pull request merged**
