### PR TITLE
Disable saved view for SSOTInfobloxConfig 

### LINKED ISSUE #530: Unable to view Infoblox Configuration List
### Environment
* Python version: 3.11.9
* Nautobot version:  2.3.1
* nautobot-ssot version:  3.0.1

### Expected Behavior
To be presented with a page listing any existing Infoblox Configurations, and ability to create a new Configuration.

### Observed Behavior
Traceback with: `'NoneType' object has no attribute '__name__'`
`Exception Location: | /usr/local/lib/python3.11/site-packages/nautobot/core/templatetags/helpers.py, line 798, in saved_view_modal`

### Steps to Reproduce
1. From the home page, choose Apps -> Installed Apps
2. Click the orange cog (configure) for Single Source of Truth
3. Click "Infoblox Configuration List"

### Cause/Fix
This is caused by Saved Views being implemented in Nautobot 2.3+. At [/nautobot/core/templates/generic/object_list.html , line 263](https://github.com/nautobot/nautobot/blob/15c8b869bb76eb806e4a5a44302bcc06cebf5679/nautobot/core/templates/generic/object_list.html#L263) it determines that the SSOTInfobloxConfig model is a saved view (new default setting). This model has no need for ever being a saved view.

The fix will be to set `is_saved_view_model = False` for the `class SSOTInfobloxConfig`, PR incoming.

### PR DESCRIPTION
**Pull request by nopg**
Fixes #530

### CODE REVIEW

**Comment by Kircheneer** [comment]
Thanks for the submission! Do you mind putting a

```python
# TODO: Clarify how saved views can be done for child apps
```

comment just above this so we don't forget to get to the bottom of this?

**Comment by jdrew82** [comment]
> Thanks for the submission! Do you mind putting a
> 
> ```python
> # TODO: Clarify how saved views can be done for child apps
> ```
> 
> comment just above this so we don't forget to get to the bottom of this?

I can only really see us adding this capability to the SSoT Logs and Sync History pages. We also need to add pagination to the Sync History pages.

**Comment by nopg** [comment]
> Thanks for the submission! Do you mind putting a
> 
> ```python
> # TODO: Clarify how saved views can be done for child apps
> ```
> 
> comment just above this so we don't forget to get to the bottom of this?

Done!

**Review by jdrew82 — APPROVED** [review]
LGTM!

**Pull request merged**
