### PR TITLE
Add common TypedDicts used for M2M

### PR DESCRIPTION
**Pull request by Renrut5**
Add common TypedDicts for use with many-to-many and one-to-many relationships.

### CODE REVIEW

**Comment by Kircheneer** [comment]
Thanks for the contribution! Can you add some docs that show why these exist and how to use them?

**Comment by jdrew82** [comment]
@Renrut5 Can you please update your initial comment to explain what this PR is for? Also, like @Kircheneer , can we get some documentation around these? I think it'd make sense to include these in the Modeling or Developer section(s)?

**Comment by Renrut5** [comment]
@jdrew82  @Kircheneer added some docs. Kept it simple and right under where it introduces typed dicts.

**Review by jdrew82 — APPROVED** [review]
LGTM!

**Pull request merged**
