### PR TITLE
Add custom relationship capabilities to the contrib module

### PR DESCRIPTION
**Pull request by Kircheneer**

### CODE REVIEW

**Comment by mzbroch** [comment]
@Kircheneer How can we help to get this to the final line? We'd like to see this in, so we can remove dependency. Also we can help with testing.

**Comment by Kircheneer** [comment]
Thanks @Renrut5 - I will try and push this forward then.

**Comment by Kircheneer** [comment]
Added docs and fixed linting. Ready for review.

**Review by jdrew82 — APPROVED** [review]
LGTM!

**Comment by Renrut5** [comment]
@Kircheneer, just found a bug in it so don't merge yet. Did find a potential fix, but need to verify.

**Comment by Renrut5** [comment]
@Kircheneer , it appears the issue was already addressed in your most recent commit. I have nothing to prevent merging at this time.

**Pull request merged**
