### PR TITLE
Ipfabric pydantic v2

### PR DESCRIPTION
**Pull request by jjeff07**
- Update `ipfabric` to 6.6.2 with Pydantic v2 Support (Will release stable today)
- Upadted to use IP Fabric `Device` model.
- Remove `ipfabric-diagrams`
- Added 🔒 and device count to snapshot descriptions
- Clip VLAN names exceeding character limit instead of no name.
- Clip Device Serial Number exceeding character limit instead of no serial number.
- Corrected Interface IPv4 Address Subnet.
- Add IPv6 Primary IP to interfaces.

### CODE REVIEW

**Comment by Kircheneer** [comment]
Is this PR ready to go @jjeff07? Is so, can you fix up the CI? @alhogan, would you mind giving it a look?

**Comment by jjeff07** [comment]
@Kircheneer 
I have no idea.  I cannot get the SSOT to run locally at all (any branch)  so I have no way of testing it.  I'm sure there are some things that need fixed but it just won't run for me.  I can maybe try again next week

**Comment by Kircheneer** [comment]
> @Kircheneer I have no idea. I cannot get the SSOT to run locally at all (any branch) so I have no way of testing it. I'm sure there are some things that need fixed but it just won't run for me. I can maybe try again next week

If you share a stack trace we _may_ be able to help you out!

**Comment by cordeezy2** [comment]
I still have a few updates to make. 
Also watching any changes on develop to cherry pick in as well. 

waiting on 
https://github.com/nautobot/nautobot-app-chatops/pull/300 to close before trying to merge into https://github.com/nautobot/nautobot-app-ssot/pull/349

**Pull request closed without merging**
